/*
 * This file is part of xPlay.
 *
 * xPlay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * xPlay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
#include <QMenuBar>
#include <QFileDialog>
#include <QMessageBox>

#include "xApplication.h"
#include "xPlayerConfiguration.h"
#include "xPlayerConfigurationDialog.h"

xApplication::xApplication(QWidget* parent, Qt::WindowFlags flags):
        QMainWindow(parent, flags) {
    // Setup music and movie library.
    musicLibrary = new xMusicLibrary(this);
    movieLibrary = new xMovieLibrary(this);
    // Stack for different views.
    mainView = new QStackedWidget(this);
    // Setup players and main widgets
    musicPlayer = new xMusicPlayerX(mainView);
    moviePlayer = new xMoviePlayer(mainView);
    mainMusicWidget = new xMainMusicWidget(musicPlayer, mainView);
    mainMovieWidget = new xMainMovieWidget(moviePlayer, mainView);
    mainStreamingWidget = new xMainStreamingWidget(mainView);
    mainDbus = new xPlayerDBus(mainView);
    // Add to the stack widget
    mainView->addWidget(new QWidget(mainView));
    mainView->addWidget(mainMusicWidget);
    mainView->addWidget(mainMovieWidget);
    mainView->addWidget(mainStreamingWidget);
    mainView->setCurrentWidget(mainMusicWidget);
    // Use main widget as central application widget.
    setCentralWidget(mainView);
    // Create Application menus.
    createMenus();
    // Connect music library with main music widget.
    // Commands for the music library.
    connect(mainMusicWidget, &xMainMusicWidget::scanForArtist, musicLibrary, &xMusicLibrary::scanForArtist);
    connect(mainMusicWidget, &xMainMusicWidget::scanForArtistAndAlbum, musicLibrary, &xMusicLibrary::scanForArtistAndAlbum);
    connect(mainMusicWidget, &xMainMusicWidget::scanAllAlbumsForArtist, musicLibrary, &xMusicLibrary::scanAllAlbumsForArtist);
    // Results back to the main music widget.
    connect(musicLibrary, &xMusicLibrary::scannedArtists, mainMusicWidget, &xMainMusicWidget::scannedArtists);
    connect(musicLibrary, &xMusicLibrary::scannedAlbums, mainMusicWidget, &xMainMusicWidget::scannedAlbums);
    connect(musicLibrary, &xMusicLibrary::scannedTracks, mainMusicWidget, &xMainMusicWidget::scannedTracks);
    connect(musicLibrary, &xMusicLibrary::scannedAllAlbumTracks, mainMusicWidget, &xMainMusicWidget::scannedAllAlbumTracks);
    // Connect movie library with main movie widget
    connect(mainMovieWidget, &xMainMovieWidget::scanForTag, movieLibrary, &xMovieLibrary::scanForTag);
    connect(mainMovieWidget, &xMainMovieWidget::scanForTagAndDirectory, movieLibrary, &xMovieLibrary::scanForTagAndDirectory);
    connect(mainMovieWidget, &xMainMovieWidget::playMovie, moviePlayer, &xMoviePlayer::setMovie);
    connect(mainMovieWidget, &xMainMovieWidget::showMenuBar, menuBar(), &QMenuBar::setVisible);
    // Results back to the main movie widget.
    connect(movieLibrary, &xMovieLibrary::scannedTags, mainMovieWidget, &xMainMovieWidget::scannedTags);
    connect(movieLibrary, &xMovieLibrary::scannedDirectories, mainMovieWidget, &xMainMovieWidget::scannedDirectories);
    connect(movieLibrary, &xMovieLibrary::scannedMovies, mainMovieWidget, &xMainMovieWidget::scannedMovies);
    // Do not connect main widget to music player here. It is done in the main widget
    // Connect Settings.
    connect(xPlayerConfiguration::configuration(), &xPlayerConfiguration::updatedMusicLibraryDirectory,
            this, &xApplication::setMusicLibraryDirectory);
    connect(xPlayerConfiguration::configuration(), &xPlayerConfiguration::updatedMovieLibraryTagsAndDirectories,
            this, &xApplication::setMovieLibraryTagsAndDirectories);
    connect(xPlayerConfiguration::configuration(), &xPlayerConfiguration::updatedRotelNetworkAddress,
            this, &xApplication::setRotelNetworkAddress);
    connect(xPlayerConfiguration::configuration(), &xPlayerConfiguration::updatedStreamingSites,
            this, &xApplication::setStreamingSites);
    connect(xPlayerConfiguration::configuration(), &xPlayerConfiguration::updatedStreamingSitesDefault,
            this, &xApplication::setStreamingSitesDefault);
    // Signal configuration updates.
    xPlayerConfiguration::configuration()->updatedConfiguration();
    // Connect signals generated by dbus commands.
    connect(mainDbus, &xPlayerDBus::dbus_playPause, this, &xApplication::dbus_playPause);
    connect(mainDbus, &xPlayerDBus::dbus_stop, this, &xApplication::dbus_stop);
    connect(mainDbus, &xPlayerDBus::dbus_prev, this, &xApplication::dbus_prev);
    connect(mainDbus, &xPlayerDBus::dbus_next, this, &xApplication::dbus_next);
    connect(mainDbus, &xPlayerDBus::dbus_jump, this, &xApplication::dbus_jump);
    connect(mainDbus, &xPlayerDBus::dbus_fullWindow, this, &xApplication::dbus_fullWindow);
    connect(mainDbus, &xPlayerDBus::dbus_scaleAndCrop, this, &xApplication::dbus_scaleAndCrop);
    connect(mainDbus, &xPlayerDBus::dbus_mute, this, &xApplication::dbus_mute);
    connect(mainDbus, &xPlayerDBus::dbus_changeVolume, this, &xApplication::dbus_changeVolume);
    connect(mainDbus, &xPlayerDBus::dbus_selectView, this, &xApplication::dbus_selectView);
    connect(mainDbus, &xPlayerDBus::dbus_muteRotel, this, &xApplication::dbus_muteRotel);
    connect(mainDbus, &xPlayerDBus::dbus_changeRotelVolume, this, &xApplication::dbus_changeRotelVolume);
    connect(mainDbus, &xPlayerDBus::dbus_selectRotelSource, this, &xApplication::dbus_selectRotelSource);
}

void xApplication::dbus_playPause() {
    auto currentWidget = mainView->currentWidget();
    if (currentWidget == mainMusicWidget) {
        musicPlayer->playPause();
    } else if (currentWidget == mainMovieWidget) {
        moviePlayer->playPause();
    }
}

void xApplication::dbus_stop() {
    auto currentWidget = mainView->currentWidget();
    if (currentWidget == mainMusicWidget) {
        musicPlayer->stop();
    } else if (currentWidget == mainMovieWidget) {
        moviePlayer->stop();
    }
}

void xApplication::dbus_prev() {
    if (mainView->currentWidget() == mainMusicWidget) {
        musicPlayer->prev();
    }
}

void xApplication::dbus_next() {
    if (mainView->currentWidget() == mainMusicWidget) {
        musicPlayer->next();
    }
}

void xApplication::dbus_jump(qint64 delta) {
    auto currentWidget = mainView->currentWidget();
    if (currentWidget == mainMusicWidget) {
        musicPlayer->jump(delta);
    } else if (currentWidget == mainMovieWidget) {
        moviePlayer->jump(delta);
    }
}

void xApplication::dbus_fullWindow() {
    if (mainView->currentWidget() == mainMovieWidget) {
        emit moviePlayer->toggleFullWindow();
    }
}

void xApplication::dbus_scaleAndCrop() {
    if (mainView->currentWidget() == mainMovieWidget) {
        moviePlayer->toggleScaleAndCropMode();
    }
}

void xApplication::dbus_mute() {
    // Set the volume to mute and emit the update to the volume widget.
    auto currentWidget = mainView->currentWidget();
    if (currentWidget == mainMusicWidget) {
        musicPlayer->setMuted(!musicPlayer->isMuted());
    } else if (currentWidget == mainMovieWidget) {
        moviePlayer->setMuted(!moviePlayer->isMuted());
    } else if (currentWidget == mainStreamingWidget) {
        mainStreamingWidget->setMuted(!mainStreamingWidget->isMuted());
    }
}

void xApplication::dbus_changeVolume(int delta) {
    // Set the volume and emit the update to the volume widget.
    auto currentWidget = mainView->currentWidget();
    if (currentWidget == mainMusicWidget) {
        musicPlayer->setVolume(musicPlayer->getVolume()+delta);
        emit musicPlayer->currentVolume( musicPlayer->getVolume());
    } else if (currentWidget == mainMovieWidget) {
        moviePlayer->setVolume(moviePlayer->getVolume()+delta);
        emit moviePlayer->currentVolume( moviePlayer->getVolume());
    }
}

void xApplication::dbus_selectView(const QString& view) {
    // Change view. Make menu bar visible in music and streaming view.
    if (!view.compare("music", Qt::CaseInsensitive)) {
        menuBar()->setVisible(true);
        mainView->setCurrentWidget(mainMusicWidget);
    } else if (!view.compare("movie", Qt::CaseInsensitive)) {
        mainView->setCurrentWidget(mainMovieWidget);
    } else if (!view.compare("streaming", Qt::CaseInsensitive)) {
        menuBar()->setVisible(true);
        mainView->setCurrentWidget(mainStreamingWidget);
    }
}

void xApplication::dbus_muteRotel() {
    // Mute the Rotel amp.
    auto rotelControls = xPlayerRotelControls::controls();
    rotelControls->setMuted(!rotelControls->isMuted());
}

void xApplication::dbus_changeRotelVolume(int delta) {
    // Set the volume for the Rotel amp.
    auto rotelControls = xPlayerRotelControls::controls();
    rotelControls->setVolume(rotelControls->getVolume()+delta);
}

void xApplication::dbus_selectRotelSource(const QString& source) {
    // Set a new source for the Rotel amp.
    xPlayerRotelControls::controls()->setSource(source);
}

void xApplication::setMusicLibraryDirectory() {
    auto musicLibraryDirectory=xPlayerConfiguration::configuration()->getMusicLibraryDirectory();
    musicLibrary->setBaseDirectory(std::filesystem::path(musicLibraryDirectory.toStdString()));
    musicPlayer->setBaseDirectory(musicLibraryDirectory);
    qInfo() << "Update music library path to " << musicLibraryDirectory;
}

void xApplication::setRotelNetworkAddress() {
    auto [rotelAddress,rotelPort] = xPlayerConfiguration::configuration()->getRotelNetworkAddress();
    xPlayerRotelControls::controls()->connect(rotelAddress, rotelPort);
}

void xApplication::setMovieLibraryTagsAndDirectories() {
    movieLibrary->setBaseDirectories(xPlayerConfiguration::configuration()->getMovieLibraryTagAndDirectoryPath());
}

void xApplication::setStreamingSites() {
    mainStreamingWidget->setSites(xPlayerConfiguration::configuration()->getStreamingSites());
}

void xApplication::setStreamingSitesDefault() {
    mainStreamingWidget->setSitesDefault(xPlayerConfiguration::configuration()->getStreamingSitesDefault());
}

void xApplication::createMenus() {
    // Create actions for file menu.
    auto fileMenuConfigure = new QAction("&Configure", this);
    auto fileMenuRescanMusicLibrary = new QAction("Rescan M&usic Library", this);
    auto fileMenuRescanMovieLibrary = new QAction("Rescan M&ovie Library", this);
    auto fileMenuExitAction = new QAction(tr("&Exit"), this);
    // Connect actions from file menu.
    connect(fileMenuConfigure, &QAction::triggered, this, &xApplication::configure);
    connect(fileMenuRescanMusicLibrary, &QAction::triggered, this, &xApplication::setMusicLibraryDirectory);
    connect(fileMenuRescanMovieLibrary, &QAction::triggered, this, &xApplication::setMovieLibraryTagsAndDirectories);
    connect(fileMenuExitAction, &QAction::triggered, this, &xApplication::close);
    // Create file menu.
    auto fileMenu = menuBar()->addMenu(tr("&File"));
    fileMenu->addAction(fileMenuConfigure);
    fileMenu->addSeparator();
    fileMenu->addAction(fileMenuRescanMusicLibrary);
    fileMenu->addAction(fileMenuRescanMovieLibrary);
    fileMenu->addSeparator();
    fileMenu->addAction(fileMenuExitAction);
    // Create actions for view menu.
    auto viewMenuSelectMusic = new QAction("Select M&usic View", this);
    auto viewMenuSelectMovie = new QAction("Select M&ovie View", this);
    auto viewMenuSelectStreaming = new QAction("Select Str&eaming View", this);
    // Connect actions from view menu.
    connect(viewMenuSelectMusic, &QAction::triggered, [=]() { mainView->setCurrentWidget(mainMusicWidget); });
    connect(viewMenuSelectMovie, &QAction::triggered, [=]() { mainView->setCurrentWidget(mainMovieWidget); });
    connect(viewMenuSelectStreaming, &QAction::triggered, [=]() { mainView->setCurrentWidget(mainStreamingWidget); });
    // Create view menu.
    auto viewMenu = menuBar()->addMenu(tr("&View"));
    viewMenu->addAction(viewMenuSelectMusic);
    viewMenu->addAction(viewMenuSelectMovie);
    viewMenu->addAction(viewMenuSelectStreaming);
    // Create actions for help menu
    auto helpMenuAboutQt = new QAction("About Qt", this);
    auto helpMenuAboutQwt = new QAction("About Qwt", this);
    // Connect actions from view menu.
    connect(helpMenuAboutQt, &QAction::triggered, [=]() { QMessageBox::aboutQt(this, "About Qt"); });
    connect(helpMenuAboutQwt, &QAction::triggered, [=]() { QMessageBox::about(this, "About Qwt",
        // The text for Qwt taken from their website and license.
        "<p><b>Qwt - Qt Widgets for Technical Applications</b></p>"
        "<p>The Qwt library contains GUI Components and utility classes which are primarily "
        "useful for programs with a technical background. Beside a framework for 2D plots it "
        "provides scales, sliders, dials, compasses, thermometers, wheels and knobs to "
        "control or display values, arrays, or ranges of type double.</p>"
        "<p><i>xPlay is based in part on the work of the Qwt project (http://qwt.sf.net).</i></p>"); });
    // Create help menu.
    auto helpMenu = menuBar()->addMenu(tr("&Help"));
    helpMenu->addAction(helpMenuAboutQt);
    helpMenu->addAction(helpMenuAboutQwt);
}

void xApplication::configure() {
    xPlayerConfigurationDialog configurationDialog;
    configurationDialog.show();
    configurationDialog.exec();
}

